import { Inter } from 'next/font/google';
import Sidebar from '@/components/Sidebar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
//inter.className

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body className="relative">
				<Sidebar className="fixed top-0 left-0 h-screen w-12 md:w-16 flex flex-col items-center justify-center bg-slate-200" />
				<main className='ml-12 md:ml-16'>{children}</main>
			</body>
		</html>
	);
}
